export const UI_STRINGS = {
  APP_TITLE: "🎸 Cancionero de Guitarra",
  NEW_SONG_BUTTON: "Nueva Canción",
  NEW_SONG_TITLE: "Canción sin título",
  NEW_SONG_ARTIST: "Artista Desconocido",
  NEW_SONG_CONTENT: "[C]Estrofa 1...",

  // Sidebar Tabs
  SONGS_TAB: "Canciones",
  SETLISTS_TAB: "Repertorios",

  // Song List
  SEARCH_PLACEHOLDER: "Buscar canciones...",
  NO_SONGS_FOUND: "No se encontraron canciones.",
  DELETE_SONG_ARIA_LABEL: "Eliminar la canción",

  // Setlist
  NEW_SETLIST_BUTTON: "Nuevo Repertorio",
  NEW_SETLIST_TITLE: "Nuevo Repertorio",
  NO_SETLISTS_FOUND: "No tienes repertorios.",
  EDIT_SETLIST_TITLE: "Editando Repertorio",
  SETLIST_NAME_PLACEHOLDER: "Nombre del Repertorio",
  ADD_SONGS_TO_SETLIST_BUTTON: "Añadir Canciones",
  SETLIST_EMPTY_MESSAGE: "Este repertorio está vacío. Añade algunas canciones para empezar.",
  DELETE_SETLIST_ARIA_LABEL: "Eliminar el repertorio",
  ADD_SONGS_MODAL_TITLE: "Añadir Canciones al Repertorio",
  NO_MORE_SONGS_TO_ADD: "Todas tus canciones ya están en este repertorio.",
  ADD_SELECTED_SONGS_BUTTON: "Añadir Seleccionadas",

  // Editor
  TITLE_PLACEHOLDER: "Título de la Canción",
  ARTIST_PLACEHOLDER: "Artista",
  EDITOR_PLACEHOLDER: "Introduce la letra y los acordes de la canción en formato ChordPro...\nEj: {title: Mi Canción}\n    {artist: Yo Mismo}\n    {capo: 2}\n\n    *Coro:*\n    [C]Esta es la letra con un [G]acorde.",
  SAVE_CHANGES_BUTTON: "Guardar Cambios",
  SAVED_BUTTON: "Guardado",
  TRANSPOSE_UP_BUTTON: "Subir Tono",
  TRANSPOSE_DOWN_BUTTON: "Bajar Tono",
  RESET_TRANSPOSE_BUTTON_TITLE: "Resetear Tonalidad",
  RETURN_TO_SETLIST_BUTTON: "Volver al repertorio",
  INSERT_CHORD_BUTTON: "Insertar Acorde",
  SUGGEST_CHORDS_BUTTON: "Sugerir Acordes",
  SUGGESTING_CHORDS_BUTTON: "Sugiriendo...",
  SUGGEST_CHORDS_TOOLTIP: "Selecciona una estrofa o coro y la IA añadirá acordes",
  EXPORT_PDF_BUTTON: "Exportar PDF",
  EXPORT_JSON_BUTTON: "Exportar JSON",
  EXPORTING_PDF_BUTTON: "Generando...",
  HIDE_CHORDS_BUTTON: "Ocultar Acordes",
  SHOW_CHORDS_BUTTON: "Mostrar Acordes",
  PERFORMANCE_MODE_BUTTON: "Interpretación",
  TOGGLE_CHORDS_VIEW_TITLE: "Alternar visibilidad de acordes",
  UNSAVED_CHANGES_WARNING: "Tienes cambios sin guardar. ¿Estás seguro de que quieres salir?",
  CHORD_PALETTE_TITLE: "Acordes en la Canción",
  COMMON_CHORDS_TITLE: "Acordes Comunes",

  // Song Settings in Editor
  SONG_SETTINGS_TITLE: "Ajustes de Interpretación",
  BPM_LABEL: "BPM",
  TIME_SIGNATURE_LABEL: "Compás (ej. 4/4)",
  BACKING_TRACK_LABEL: "Pista de Acompañamiento",
  UPLOAD_TRACK_BUTTON: "Subir Pista",
  REMOVE_TRACK_BUTTON: "Quitar",
  AUDIO_SAVED_INFO: "La pista de audio se guarda en tu dispositivo y estará disponible en futuras sesiones.",

  // Preview & Chords
  PREVIEW_TITLE: "Vista Previa",
  CHORDS_TITLE: "Acordes",
  CHORD_DIAGRAM_NOT_AVAILABLE: "Diagrama de acorde no disponible",
  CAPO_ON_FRET: "Capo en traste",
  KEY_LABEL: "Tono",

  // Welcome Screen
  WELCOME_TITLE: "Bienvenido a tu Cancionero",
  WELCOME_MESSAGE: "Organiza tus canciones, crea repertorios y prepárate para tocar. Empieza creando una canción o tu primer repertorio.",
  CREATE_FIRST_SONG_BUTTON: "Crear Canción",
  CREATE_FIRST_SETLIST_BUTTON: "Crear Repertorio",

  // Modals
  CHORD_PICKER_TITLE: "Selecciona un Acorde",
  CHORD_BUILDER_TITLE: "Constructor de Acordes",
  CHORD_BUILDER_TAB: "Constructor Rápido",
  VISUAL_EDITOR_TAB: "Editor Visual",
  CHORD_NAME_LABEL: "Nombre del Acorde",
  CHORD_NAME_PLACEHOLDER: "Ej: F#m7(b5)",
  BASE_FRET_LABEL: "Traste Base",
  RESET_SHAPE_BUTTON: "Reiniciar Diagrama",
  CHORD_BUILDER_ROOT_NOTE: "Nota Raíz",
  CHORD_BUILDER_QUALITY: "Calidad",
  CHORD_BUILDER_EXTENSIONS: "Tensiones",
  CHORD_BUILDER_BASS: "Bajo (Inversión)",
  CHORD_BUILDER_INSERT: "Insertar",
  CHORD_BUILDER_CLEAR: "Limpiar",
  SEARCH_CHORD_PLACEHOLDER: "Buscar acorde...",
  CLOSE_MODAL_ARIA_LABEL: "Cerrar",
  DELETE_CONFIRM_TITLE: "Confirmar Eliminación",
  DELETE_SONG_CONFIRM_MESSAGE: "¿Estás seguro de que quieres eliminar la canción",
  DELETE_SETLIST_CONFIRM_TITLE: "Eliminar Repertorio",
  DELETE_SETLIST_CONFIRM_MESSAGE: "¿Estás seguro de que quieres eliminar el repertorio",
  CANCEL_BUTTON: "Cancelar",
  DELETE_BUTTON: "Eliminar",
  IMPORT_BUTTON: "Importar",
  IMPORT_SONGS_CONFIRM_TITLE: "Confirmar Importación de Canciones",
  IMPORT_SONGS_CONFIRM_MESSAGE: "Se añadirán canciones del archivo. Las canciones existentes con el mismo título y artista serán omitidas. ¿Continuar?",
  IMPORT_SETLISTS_CONFIRM_TITLE: "Confirmar Importación de Repertorios",
  IMPORT_SETLISTS_CONFIRM_MESSAGE: "Se añadirán repertorios del archivo. Los repertorios existentes con el mismo nombre serán omitidos. ¿Continuar?",
  MORE_OPTIONS_ARIA_LABEL: "Más opciones",
  IMPORT_SONGS_BUTTON: "Importar Canciones (JSON)",
  IMPORT_PDF_BUTTON: "Importar desde PDF",
  IMPORT_SETLISTS_BUTTON: "Importar Repertorios",
  EXPORT_SONGS_BUTTON: "Exportar Canciones",
  EXPORT_SETLISTS_BUTTON: "Exportar Repertorios",
  PDF_EXPORT_OPTIONS_TITLE: "Opciones de Exportación PDF",
  PDF_LAYOUT_LABEL: "Diseño",
  PDF_COLUMNS_ONE: "1 Columna",
  PDF_COLUMNS_TWO: "2 Columnas",
  PDF_INCLUDE_CHORDS_LABEL: "Incluir diagramas de acordes",
  EXPORT_BUTTON: "Exportar",

  // Performance Mode
  AUTOSCROLL_DURATION_LABEL: "Duración:",
  METRONOME_TITLE: "Metrónomo",
  PRECOUNT_LABEL: "Pre-conteo",
  PLAYER_TITLE: "Pista",
  VIEW_SETTINGS_TITLE: "Vista",
  FONT_SIZE_LABEL: "Tamaño de Fuente",
  PLAY_ARIA_LABEL: "Reproducir",
  PAUSE_ARIA_LABEL: "Pausa",
  PIN_CONTROLS_ARIA_LABEL: "Fijar controles",

  // Toasts / Notifications
  TOAST_LOAD_ERROR: "Error al cargar los datos.",
  TOAST_SAVE_ERROR: "Error al guardar los datos.",
  TOAST_SAVE_ERROR_QUOTA: "Error al guardar: almacenamiento lleno. Prueba a eliminar pistas de audio grandes de las canciones.",
  TOAST_SONG_SAVED: "Canción guardada con éxito.",
  TOAST_SONG_EXPORTED: "Canción exportada",
  TOAST_SONG_DELETED: "Canción eliminada.",
  TOAST_SETLIST_CREATED: "Repertorio creado.",
  TOAST_SETLIST_UPDATED: "Repertorio actualizado.",
  TOAST_SETLIST_DELETED: "Repertorio eliminado.",
  TOAST_PDF_NO_CONTENT: "No hay contenido para exportar.",
  TOAST_PDF_EXPORT_SUCCESS: "PDF exportado con éxito.",
  TOAST_PDF_EXPORT_ERROR: "Ocurrió un error al exportar a PDF.",
  TOAST_PDF_IMPORTING: "Analizando PDF...",
  TOAST_PDF_IMPORT_SUCCESS: "Canción importada desde PDF con éxito.",
  TOAST_PDF_IMPORT_ERROR: "Error al importar el PDF. El formato puede no ser compatible.",
  TOAST_NO_SONGS_TO_EXPORT: "No hay canciones para exportar.",
  TOAST_NO_SETLISTS_TO_EXPORT: "No hay repertorios para exportar.",
  TOAST_EXPORT_SUCCESS: "Canciones exportadas con éxito.",
  TOAST_EXPORT_SETLISTS_SUCCESS: "Repertorios exportados con éxito.",
  TOAST_EXPORT_ERROR: "Error al exportar los datos.",
  TOAST_IMPORT_SUCCESS: "canciones importadas con éxito.",
  TOAST_SETLIST_IMPORT_ERROR: "Error: El archivo de repertorios no es válido o está corrupto.",
  TOAST_IMPORT_SETLISTS_SUCCESS: "repertorios importados con éxito.",
  TOAST_IMPORT_ERROR: "Error: El archivo no es válido o está corrupto.",
  TOAST_IMPORT_FILE_READ_ERROR: "Error al leer el archivo.",
  TOAST_AUDIO_FILE_TOO_LARGE: "El archivo de audio es muy grande (límite 15MB).",
  TOAST_GEMINI_ERROR: "Error al contactar al asistente de IA.",
  TOAST_SELECT_TEXT_FIRST: "Por favor, selecciona primero un fragmento de la letra.",
};